name: "On Push/Pull Request"

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-on-pull:
    uses: "./.github/workflows/build.yml"
    with:
      latest: false
  test-on-pull:
    uses: "./.github/workflows/test.yml"
