name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1.3
        id: version_tag
        with:
          tagRegex: "v(.*)"
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        id: release
        with:
          name: "v${{ steps.version_tag.outputs.tag }}"
          tag_name: "v${{ steps.version_tag.outputs.tag }}"
          generate_release_notes: true
          append_body: true
          prerelease: false
          fail_on_unmatched_files: true
      - name: "Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: true
          releaseUrl: ${{ steps.release.outputs.url }}
          issues: false
          pullRequests: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update CHANGELOG.md"
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: CHANGELOG.md
  docker:
    needs: ['create_release']
    uses: "./.github/workflows/docker.yml"
    with:
      docker_target: production
      platforms: linux/amd64,linux/arm64
      version: ${{ inputs.version }}
      image: ${{ vars.IMAGE }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  build:
    needs: ['create_release']
    uses: "./.github/workflows/build.yml"
    with:
      version: ${{ inputs.version }}
      latest: true
