name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: olegtarasov/get-tag@v2.1.3
        id: version_tag
        with:
          tagRegex: "v(.*)"
  docker:
    needs: ['create_release']
    uses: "./.github/workflows/docker.yml"
    with:
      docker_target: production
      platforms: linux/amd64,linux/arm64
      version: ${{ inputs.version }}
      image: ${{ vars.IMAGE }}
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  build:
    needs: ['create_release']
    uses: "./.github/workflows/build.yml"
    with:
      version: ${{ inputs.version }}
      latest: true
