name: "Test Cassandra-Stress"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        java: [ '11' ]
        os: [ 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - name: Setup Ant
        uses: cedx/setup-ant@v2
        with:
          optional-tasks: true
          version: latest
      - name: Setup
        run: ant init
      - name: Test src
        run: ant build-test
      - name: Test cassandra-stress
        run: ant stress-test
